// Alert Types
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// Auth Types
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const ACCOUNT_DELETED = 'ACCOUNT_DELETED';

// Medicine Types
export const GET_MEDICINES = 'GET_MEDICINES';
export const GET_MEDICINE = 'GET_MEDICINE';
export const MEDICINE_ERROR = 'MEDICINE_ERROR';
export const ADD_MEDICINE = 'ADD_MEDICINE';
export const UPDATE_MEDICINE = 'UPDATE_MEDICINE';
export const DELETE_MEDICINE = 'DELETE_MEDICINE';
export const SEARCH_MEDICINES = 'SEARCH_MEDICINES';
export const CLEAR_MEDICINES = 'CLEAR_MEDICINES';

// Order Types
export const CREATE_ORDER = 'CREATE_ORDER';
export const GET_ORDERS = 'GET_ORDERS';
export const GET_ORDER = 'GET_ORDER';
export const ADD_ORDER = 'ADD_ORDER';
export const UPDATE_ORDER_STATUS = 'UPDATE_ORDER_STATUS';
export const UPDATE_ORDER_LOCATION = 'UPDATE_ORDER_LOCATION';
export const UPLOAD_PRESCRIPTION = 'UPLOAD_PRESCRIPTION';
export const VERIFY_PRESCRIPTION = 'VERIFY_PRESCRIPTION';
export const ORDER_ERROR = 'ORDER_ERROR';
export const CLEAR_ORDER = 'CLEAR_ORDER';
export const UPDATE_PAYMENT_STATUS = 'UPDATE_PAYMENT_STATUS';

// Inventory Types
export const GET_MEDICINE_REQUESTS = 'GET_MEDICINE_REQUESTS';
export const GET_MEDICINE_REQUEST = 'GET_MEDICINE_REQUEST';
export const ADD_MEDICINE_REQUEST = 'ADD_MEDICINE_REQUEST';
export const UPDATE_MEDICINE_REQUEST = 'UPDATE_MEDICINE_REQUEST';
export const DELETE_MEDICINE_REQUEST = 'DELETE_MEDICINE_REQUEST';
export const GET_SALT_REQUESTS = 'GET_SALT_REQUESTS';
export const GET_SALT_REQUEST = 'GET_SALT_REQUEST';
export const ADD_SALT_REQUEST = 'ADD_SALT_REQUEST';
export const UPDATE_SALT_REQUEST = 'UPDATE_SALT_REQUEST';
export const DELETE_SALT_REQUEST = 'DELETE_SALT_REQUEST';
export const INVENTORY_ERROR = 'INVENTORY_ERROR';

// Analytics Types
export const GENERATE_REPORT = 'GENERATE_REPORT';
export const GET_REPORTS = 'GET_REPORTS';
export const GET_REPORT = 'GET_REPORT';
export const ANALYTICS_ERROR = 'ANALYTICS_ERROR'; 